# _*_ coding : utf-8 _*_
'''

作者 : 解洋
时间: 2020-3-25
'''
# _*_ coding : utf-8 _*_
'''
作者 : 解洋
时间: 2020-3-24
'''


class CAgent():
    def __init__(self):
        self.class_name = 'aircraft_'

    def test(self, scenario):
        for side_k, side_v in scenario.get_sides().items():
            if len(side_v.satellites):
                # 测试卫星
                print(7)
                for sat_k, sat_v in side_v.satellites:
                    print('mount:')
                    print(sat_v.get_mounts())
                    print('senaor')
                    print(sat_v.get_sensor())
                    print('magazine')
                    print(sat_v.get_magazines())
                    print('doctine')
                    print(sat_v.get_doctrine())
                    print('loadout')
                    print(sat_v.get_loadout())
                    print('# 方位类型')
                    print(sat_v.m_BearingType)
                    print('# 方位')
                    print(sat_v.m_Bearing)
                    print('# 距离（转换为千米）')
                    print(sat_v.m_Distance)
                    print('# 高低速交替航行)')
                    print(sat_v.bSprintAndDrift)
                    print('# 载机按钮的文本描述')
                    print(sat_v.strDockAircraft)
                    print('# 类别')
                    print(sat_v.m_Category)
                    print('# 悬停')
                    print(sat_v.fHoverSpeed)
                    print('(# 低速')
                    print(sat_v.fLowSpeed)
                    print('# 巡航v')
                    print(sat_v.fCruiseSpeed)
                    print('# 军力')
                    print(sat_v.fMilitarySpeed)
                    print('# 加速')
                    print(sat_v.fAddForceSpeed)
                    print('# 机型（战斗机，多用途，加油机...)')
                    print(sat_v.m_Type)
                    print('# 宿主单元对象')
                    print(sat_v.m_CurrentHostUnit)
                    print('# 挂载方案的DBID')
                    print(sat_v.iLoadoutDBID)
                    print('# 挂载方案的GUid')
                    print(sat_v.m_LoadoutGuid)
                    print('# 获取当前行动状态')
                    print(sat_v.strAirOpsConditionString)
                    print('# 完成准备时间')
                    print(sat_v.strFinishPrepareTime)
                    print('# 快速出动信息')
                    print(sat_v.strQuickTurnAroundInfo)
                    print('# 显示燃油信息')
                    print(sat_v.strFuelState)
                    print('# 期望高度')
                    print(sat_v.fDesiredAltitude)
                    print('# 维护状态')
                    print(sat_v.m_MaintenanceLevel)
                    print(sat_v.fFuelConsumptionCruise)
                    print(sat_v.fAbnTime)
                    print(sat_v.iFuelRecsMaxQuantity)
                    print('# 当前油量')
                    print(sat_v.iCurrentFuelQuantity)
                    print('# 是否快速出动')
                    print(sat_v.bQuickTurnaround_Enabled)
                    print('# 是否有空中加油能力')
                    print(sat_v.bIsAirRefuelingCapable)
                    print('# 加油队列header)')
                    print(sat_v.strShowTankerHeader)
                    print('# 加油队列明细')
                    print(sat_v.m_ShowTanker)
                    print('# 可受油探管加油')
                    print(sat_v.m_bProbeRefuelling)
                    print('# 可输油管加油')
                    print(sat_v.m_bBoomRefuelling)
                    print('# 航路点名称')
                    print(sat_v.strWayPointName)
                    print('# 航路点描述')
                    print(sat_v.strWayPointDescription)
                    print('# 航路点剩余航行距离')
                    print(sat_v.strWayPointDTG)
                    print('# 航路点剩余航行时间')
                    print(sat_v.WayPointTTG)
                    print('# 航路点需要燃油数')
                    print(sat_v.strWayPointFuel)
                    print(sat_v.strGuid)
                    print('# 活动单元传感器列表')
                    print(sat_v.sensors)
                    print('# 活动单元挂架')
                    print(sat_v.mounts)
                    print('# 活动单元弹药库')
                    print(sat_v.magazines)
                    print('# 航路点')
                    print(sat_v.way_points)
                    print('# 对象类名')
                    print(sat_v.ClassName)
                    print('# 名称')
                    print(sat_v.strName)
                    print('# Guid')
                    print(sat_v.strGuid)
                    print('# 地理高度')
                    print(sat_v.fAltitude_AGL)
                    print('# 海拔高度')
                    print(sat_v.iAltitude_ASL)
                    print('# 所在推演方ID')
                    print(sat_v.m_Side)
                    print('# 单元类别')
                    print(sat_v.strUnitClass)
                    print('# 当前纬度')
                    print(sat_v.dLatitude)
                    print('# 当前经度')
                    print(sat_v.dLongitude)
                    print('# 当前朝向')
                    print(sat_v.fCurrentHeading)
                    print('# 当前速度')
                    print(sat_v.fCurrentSpeed)
                    print('# 当前海拔高度')
                    print(sat_v.fCurrentAltitude_ASL)
                    print('# 倾斜角')
                    print(sat_v.fPitch)
                    print('# 翻转角')
                    print(sat_v.fRoll)
                    print('# 获取期望速度')
                    print(sat_v.fDesiredSpeed)
                    print('# 获取最大油门')
                    print(sat_v.m_MaxThrottle)
                    print('# 最大速度')
                    print(sat_v.fMaxSpeed)
                    print('# 最小速度')
                    print(sat_v.fMinSpeed)
                    print('# 当前高度')
                    print(sat_v.fCurrentAlt)
                    print('# 期望高度')
                    print(sat_v.fDesiredAlt)
                    print('# 最大高度')
                    print(sat_v.fMaxAltitude)
                    print('# 最小高度')
                    print(sat_v.fMinAltitude)
                    print('# 军标ID')
                    print(sat_v.strIconType)
                    print('# 普通军标')
                    print(sat_v.strCommonIcon)
                    print('# 数据库ID')
                    print(sat_v.iDBID)
                    print('# 是否可操作')
                    print(sat_v.bIsOperating)
                    print('# 编组ID')
                    print(sat_v.m_ParentGroup)
                    print('# 停靠的设施的ID(关系)')
                    print(sat_v.m_DockedUnits)
                    print('# 单元的停靠设施(部件)')
                    print(sat_v.m_DockFacilitiesComponent)
                    print('# 停靠的飞机的ID(关系)')
                    print(sat_v.m_DockAircrafts)
                    print('# 单元的航空设施(部件)')
                    print(sat_v.m_AirFacilitiesComponent)
                    print('# 单元的通信设备及数据链(部件)')
                    print(sat_v.m_CommDevices)
                    print('# 单元的引擎(部件')
                    print(sat_v.m_Engines)
                    print('# 传感器，需要构建对象类,所以只传ID')
                    print(sat_v.m_Sensors)
                    print('# 挂架')
                    print(sat_v.m_Mounts)
                    print('# 毁伤状态')
                    print(sat_v.strDamageState)
                    print('# 失火')
                    print(sat_v.iFireIntensityLevel)
                    print('# 进水')
                    print(sat_v.iFloodingIntensityLevel)
                    print('# 分配的任务')
                    print(sat_v.m_AssignedMission)
                    print('# 作战条令')
                    print(sat_v.m_Doctrine)
                    print('# 系统右栏->对象信息->作战单元武器')
                    print(sat_v.m_UnitWeapons)
                    print('# 路径点')
                    print(sat_v.m_WayPoints)
                    print('# 训练水平')
                    print(sat_v.m_ProficiencyLevel)
                    print('# 是否是护卫角色')
                    print(sat_v.bIsEscortRole)
                    print('# 当前油门')
                    print(sat_v.m_CurrentThrottle)
                    print('# 通讯设备是否断开')
                    print(sat_v.bIsCommsOnLine)
                    print(sat_v.bIsIsolatedPOVObject)
                    print('# 地形跟随')
                    print(sat_v.bTerrainFollowing)
                    print(sat_v.bIsRegroupNeeded)
                    print('# 保持阵位')
                    print(sat_v.bHoldPosition)
                    print('# 是否可自动探测')
                    print(sat_v.bAutoDetectable)
                    print('# 当前货物')
                    print(sat_v.m_Cargo)
                    print('# 燃油百分比，作战单元燃油栏第一个进度条的值')
                    print(sat_v.dFuelPercentage)
                    print('# 获取AI对象的目标集合# 获取活动单元AI对象的每个目标对应显示不同的颜色集合')
                    print(sat_v.m_AITargets)
                    print('# 获取活动单元AI对象的每个目标对应显示不同的颜色集合')
                    print(sat_v.m_AITargetsCanFiretheTargetByWCSAndWeaponQty)
                    print('# 获取单元的通讯链集合')
                    print(sat_v.m_CommLink)
                    print('# 获取传感器0')
                    print(sat_v.m_NoneMCMSensors)
                    print('# 获取显示"干扰"或"被干扰"')
                    print(sat_v.iDisturbState)
                    print('# 单元所属多个任务数量')
                    print(sat_v.iMultipleMissionCount)
                    print('# 单元所属多个任务guid拼接')
                    print(sat_v.m_MultipleMissionGUIDs)
                    print('# 是否遵守电磁管控')
                    print(sat_v.bObeysEMCON)
                    print('# 武器预设的打击航线')
                    print(sat_v.m_strContactWeaponWayGuid)
                    print('# 停靠参数是否包含码头')
                    print(sat_v.bDockingOpsHasPier)
                    print('弹药库')
                    print(sat_v.m_Magazines)
                    print('被摧毁')
                    print(sat_v.dPBComponentsDestroyedWidth)
                    print("轻度")
                    print(sat_v.dPBComponentsLightDamageWidth)
                    print('# 中度')
                    print(sat_v.dPBComponentsMediumDamageWidth)
                    print('''# 重度''')
                    print(sat_v.dPBComponentsHeavyDamageWidth)
                    print('''# 重度''')
                    print(sat_v.dPBComponentsHeavyDamageWidth)
                    print('''# 正常''')
                    print(sat_v.dPBComponentsOKWidth)
                    print('''# 配属基地''')
                    print(sat_v.m_HostActiveUnit)
                    print(''' # 状态''')
                    print(sat_v.strActiveUnitStatus)
                    print('''# 精简''')
                    print(sat_v.doctrine)
                    sat_v.set_radar_shutdown('true')
                    sat_v.set_sonar_shutdown('true')
                    sat_v.set_oecm_shutdown('true')
            scenario.mozi_server.run_simulate()
            # self.mozi_server.run_simulate()
            # self.mozi_server.run_simulate()
