# battle: https://github.com/wsjeon/maddpg-rllib
group: "Gym"
name: "share/ddpg_cartpole"

training:
  interface:
    type: "independent"
    population_size: -1
    use_init_population_pool: False
  config:
    # control the frequency of remote parameter update
    use_cuda: True
    update_interval: 1
    saving_interval: 10
    batch_size: 128
    optimizer: "Adam"
    actor_lr: 0.01
    critic_lr: 0.001
    tau: 0.01  # soft update
    grad_norm_clipping: 2.0

rollout_worker:
  callback: simultaneous
  stopper:
    name: simple_rollout
    config:
      max_step: 1250
  num_threads: 4
  num_env_per_thread: 2
  num_eval_threads: 5
  batch_mode: time_step
  post_processor_types:
    - default
  use_subproc_env: False
  task_config:
    max_step: 200
    fragment_length: 200

evaluation:
  fragment_length: 200
  num_episodes: 1

env_description:
  creator: Gym
  config:
    env_id: CartPole-v0

algorithms:
  DDPG:
    name: "DDPG"
    model_config:
      actor:
        network: mlp
        layers:
          - units: 64
            activation: ReLU
          - units: 64
            activation: ReLU
        output:
          activation: False
      critic:
        network: mlp
        layers:
          - units: 64
            activation: ReLU
          - units: 64
            activation: ReLU
        output:
          activation: False

    # set hyper parameter
    custom_config:
      gamma: 0.99

global_evaluator:
  name: "generic"

dataset_config:
  episode_capacity: 1000000
  learning_start: 200

